### ISSUE TITLE
Crash on startup 

### ISSUE THREAD

**Issue by jburrows82** [shadowfacts/Endergizer#1]
MC 1.10.2
Forge *.2075
Endergizer/Forgelin 1.04

java.lang.IllegalArgumentException: Parameter specified as non-null is null: method net.shadowfacts.endergizer.RecipeBattery.func_77569_a, parameter world

[Crash](http://pastebin.com/jTG99M9n)
[fml-client-latest.txt](https://github.com/shadowfacts/Endergizer/files/440961/fml-client-latest.txt)

**Comment by shadowfacts** [comment]
1da68902c1bd5ca4c9ae0db9656abfb54eaf088b

Fixed in 1.0.5, which is currently pending approval on CurseForge.
