### ISSUE TITLE
Crash at startup - net/shadowfacts/endergizer/block/battery/BlockEnderBattery$initItemModel$1

### ISSUE THREAD

**Issue by silent-mobious** [shadowfacts/Endergizer#3]
http://pastebin.com/uBK98syc

I've tried with both Endergizer-1.10.2-1.0.5 and Endergizer-1.10.2-1.1.0, same failure for each on startup.  Also same for forge-1.10.2-12.18.1.2079-universal.jar and forge-1.10.2-12.18.1.2092-universal.jar.  The server loads without issue without the mod, and there are several other of your mods in play that have no issues.

[Server thread/ERROR] [FML/]: Caught exception from endergizer
java.lang.NoClassDefFoundError: net/shadowfacts/endergizer/block/battery/BlockEnderBattery$initItemModel$1

**Comment by shadowfacts** [comment]
Update ShadowMC to [3.4.5](https://minecraft.curseforge.com/projects/shadowmc/files/2331015).

**Comment by silent-mobious** [comment]
That did it, confirmed working.  Thanks a lot for the quick fix!
